### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by pipermerriam** [pipermerriam/ethereum-erc190#3]
Need to setup travis-ci.  Mirroring the `.travis.yml` and `tox.ini` files from https://github.com/pipermerriam/ethereum-utils should be a good starting point.  we can drop testing against `2.7` and `3.4`.  Would be good to add testing against `3.6`

**Comment by njgheorghita** [comment]
@pipermerriam I forgot to reference this in my pr - should be closable.
