### ISSUE TITLE
Expose simple properties on the Package object

### ISSUE THREAD

**Issue by pipermerriam** [pipermerriam/ethereum-erc190#6]
### What needs to be done?

Packages have a few simple properties:

* [`package_name`](https://github.com/ethpm/ethpm-spec/blob/master/release-lockfile.spec.md#package-name-package_name)
* [`version`](https://github.com/ethpm/ethpm-spec/blob/master/release-lockfile.spec.md#version-version)

These properties should be exposed on the `Package` object through the `Package.name` and `Package.version` properties.

```python
def name(self):
   ... # return the package name pulled from the package info
```

Additionally, implement a `__repr__` function on the `Package` object which returns a string formatted like `<Package {package_name}=={version})>`.

> The package named `tokens` at version `1.2.3` would return the string `"<Package owned==1.2.3>"` when repr is called on it.

**Comment by carver** [comment]
The `(name, version)` tuple is non-unique, right? Maybe it's worth adding more info here to get to uniqueness (or close enough).  I imagine the first 20 characters of the content hash are sufficient. Or maybe there's some other attribute that's better.

**Comment by pipermerriam** [comment]
>  I imagine the first 20 characters of the content hash are sufficient. Or maybe there's some other attribute that's better.

I'm 👍 on this to be done in a separate issue which exposes a new property `Package.hash` which returns the keccak256 hash of the package contents.

**Comment by pipermerriam** [comment]
Also, see https://github.com/ethpm/ethpm-spec/issues/77 which should help with hashing packages in a consistent manner.
